spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: usermicroservice
          uri: lb://usermicroservice
          predicates:
            - Path=/api/users/**
        - id: productmicroservice
          uri: lb://productmicroservice
          predicates:
            - Path=/api/products/**
  eureka:
    client:
      service-url:
        defaultZone:
          - http://localhost:8761/eureka/